Using latest vault API

diff --git a/stages/early/files/vault-request-key b/stages/early/files/vault-request-key
--- a/stages/early/files/vault-request-key
+++ b/stages/early/files/vault-request-key
@@ -6,8 +6,18 @@ function request_key() {
 	REQUEST_TOKEN=`curl -s -XPOST --data-urlencode "token=${API_TOKEN}" https://api.rcmd.space/internal/token/get`
 	KEY=${1}
 	DIRECTORY=${2}
-	OUTPUT=`curl --fail -s -XPOST --data-urlencode "token=${REQUEST_TOKEN}" --data-urlencode "key=${KEY}" --data-urlencode "directory=${DIRECTORY}" https://api.rcmd.space/internal/vault/request-key`
+	OUTPUT=`curl -s -XPOST --data-urlencode "token=${REQUEST_TOKEN}" --data-urlencode "key=${KEY}" --data-urlencode "directory=${DIRECTORY}" https://api.rcmd.space/internal/vault/request-key`
 	echo "${OUTPUT}"
 }
 
-request_key ${1} ${2}
+DATA=$(request_key ${1} ${2})
+
+STATUS=$(echo "${DATA}" | jq -r '.status')
+
+if [ $STATUS = "200"]; then
+	echo "${DATA}" | jq -r '.data' | base64 -d
+	exit 0
+else
+	echo "Failed to request a key"
+	exit 1
+fi
